<?php
/**
 * Created by PhpStorm.
 * User: CYKn
 * Date: 2019/5/23 0023
 * Time: 下午 3:36
 */
namespace app\admin\controller;

use app\common\controller\Common;
use app\common\tools;
use think\Request;

class Base extends Common
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $request = Request::instance();
        $admin_id = session('admin_ID');
        $rule = parse_url($request->url())['path']; //获取访问的的url，request()
        $isRule = (new tools\Auth())->check($admin_id,$rule);
        if (!empty($isRule)) {
            return true;
        } else {
//            header("Location:/admin/Authority/index");
//            exit();
        }
    }
}